const projectsData = [
  {
    id: 1,
    img: require('./imgs/book.png'),
    title: 'Book lists review React App',
    shortTitle: 'Book lists',
    desc: 'My first React App, created fron scratch. This is my own book lists with my own review. I included various functionalities, everything is dynamic (star ratings, buttons choice by genres or authors...)',
    skills: ['React Js', 'HTML', 'CSS', 'Responsive Design', 'Github', 'GIT'],
    linkWeb: 'https://booklist-app-kevin.netlify.app/',
    linkGit: 'https://github.com/beyondthefruit/Booklist',
  },
  {
    id: 2,
    img: require('./imgs/boc1.png'),
    title: 'Boards of Canada webpage Javascript',
    shortTitle: 'Boards of Canada',
    desc: "Probably my favourite music band. I've made a couple of web projects on this band since I started my tech journey. Made with Javascript, Buttons are dynamic",
    skills: ['Javascript', 'HTML', 'CSS', 'Responsive Design', 'Github', 'GIT'],
    linkWeb: 'https://boc-fanpage-js.netlify.app/',
    linkGit: 'https://github.com/beyondthefruit/JS-BOC-FANPAGE',
  },
  {
    id: 3,
    img: require('./imgs/darkmode.png'),
    title: 'Simple dark mode',
    shortTitle: 'Dark mode',
    desc: 'Quick project built during my javascript course',
    skills: ['Javascript', 'HTML', 'CSS', 'Github', 'GIT'],
    linkWeb: 'https://js-darkmode-beyond.netlify.app/',
    linkGit: 'https://github.com/beyondthefruit/JS-darkmode',
  },
  {
    id: 4,
    img: require('./imgs/menu.png'),
    title: 'Restaurant menu Javascript',
    shortTitle: 'Menu',
    desc: 'Project built during my javascript course, buttons are dynamic',
    skills: ['Javascript', 'HTML', 'CSS', 'Github', 'GIT'],
    linkWeb: 'https://menu-js-beyond.netlify.app/',
    linkGit: 'https://github.com/beyondthefruit/menu-JS',
  },
  {
    id: 5,
    img: require('./imgs/tours.png'),
    title: 'Travel tours React',
    shortTitle: 'Tours',
    desc: 'Project built during my react course. Many functionalities (buttons show more, delete specific tours)',
    skills: ['React Js', 'HTML', 'CSS', 'Github', 'GIT'],
    linkWeb: 'https://travel-tours-react-beyond.netlify.app/',
    linkGit: 'https://github.com/beyondthefruit/travel-tours-react',
  },
  {
    id: 6,
    img: require('./imgs/reviews.png'),
    title: 'Reviews React',
    shortTitle: 'Reviews',
    desc: 'Project built during my react course. Buttons to display next and previous reviews, random reviews etc',
    skills: ['React Js', 'HTML', 'CSS', 'Github', 'GIT'],
    linkWeb: 'https://reviews-react-beyond.netlify.app/',
    linkGit: 'https://github.com/beyondthefruit/reviews-react',
  },
  {
    id: 7,
    img: require('./imgs/menu.png'),
    title: 'Restaurant menu React',
    shortTitle: 'Menu',
    desc: 'Project built during my React course, buttons are dynamic. Similar to the javascript project but this time with react',
    skills: ['React Js', 'HTML', 'CSS', 'Github', 'GIT'],
    linkWeb: 'https://menu-react-beyond.netlify.app/',
    linkGit: 'https://github.com/beyondthefruit/menu-react',
  },
  {
    id: 8,
    img: require('./imgs/playlist.png'),
    title: 'Playlist React App',
    shortTitle: 'Playlist',
    desc: 'Project built in pair programming with a software developer. I used Styled components for this project',
    skills: [
      'React Js',
      'Styled-components',
      'Responsive Design',
      'Github',
      'GIT',
    ],
    linkWeb: 'https://react-playlist.netlify.app/',
    linkGit: 'https://github.com/julianoiret/playlist-react',
  },
  {
    id: 9,
    img: require('./imgs/profile.png'),
    title: 'Basic front end challenge',
    shortTitle: 'Profile card',
    desc: 'Front end challenge. I used SCSS for this project',
    skills: ['HTML', 'SCSS', 'Responsive Design'],
    linkWeb: 'https://basic-frontend-challenge-beyond.netlify.app/',
    linkGit: 'https://github.com/beyondthefruit/social-profile-card-challenge',
  },
  {
    id: 10,
    img: require('./imgs/catstronaut.png'),
    title: 'Catstronaut Space Academy',
    shortTitle: 'Catstronaut',
    desc: 'Full-stack project Apollo GrahQl, part of the certification Graph Developer Associate',
    skills: ['Apollo GraphQL', 'React Js'],
    linkWeb: 'https://catstronauts--client-kevin.herokuapp.com/',
    linkGit: 'https://github.com/beyondthefruit/odyssey-lift-off-part5-server',
  },
  {
    id: 11,
    img: require('./imgs/portfolio.png'),
    title: 'Portfolio',
    shortTitle: 'Portfolio',
    desc: 'My own portfolio from scratch',
    skills: ['React Js', 'CSS', 'Responsive Design', 'Github', 'GIT'],
    linkWeb: 'https://catstronauts--client-kevin.herokuapp.com/',
    linkGit: 'https://github.com/beyondthefruit/portfolio-react',
  },
];
export default projectsData;
