const projectsData = [
  {
    id: 1,
    img: require('./imgs/book.png'),
    title: 'Book lists review React App',
    shortTitle: 'Book lists',
    desc: 'My first React App, created fron scratch. This is my own book lists with my own review. I included various functionalities, everything is dynamic (review star ratings, buttons choice by genres or authors...)',
    skills: [
      'React Js',
      'HTML',
      'CSS var()',
      'FLEX/GRID',
      'Responsive Design',
      'Github',
      'GIT',
    ],
    link: 'https://booklist-app-kevin.netlify.app/',
  },
  {
    id: 2,
    img: require('./imgs/boc.png'),
    title: 'Board of Canada webpage Javascript',
    shortTitle: 'Board of Canada',
    desc: "Probably my favourite music band. I've made a couple of web projects on this band since I started my tech journey. Made with Javascript, Buttons are dynamic",
    skills: [
      'Javascript Js',
      'HTML',
      'CSS var()',
      'FLEX/GRID',
      'Responsive Design',
      'Github',
      'GIT',
    ],
    link: 'https://booklist-app-kevin.netlify.app/',
  },
  {
    id: 3,
    img: require('./imgs/darkmode.png'),
    title: 'Simple dark mode',
    shortTitle: 'Board of Canada',
    desc: 'Quick project built during my javascript course',
    skills: ['Javascript Js', 'HTML', 'CSS var()', 'Github', 'GIT'],
    link: 'https://js-darkmode-beyond.netlify.app/',
  },
  {
    id: 4,
    img: require('./imgs/menu.png'),
    title: 'Restaurant menu Javascript',
    shortTitle: 'Menu',
    desc: 'Project built during my javascript course, buttons are dynamic',
    skills: [
      'Javascript Js',
      'HTML',
      'CSS var()',
      'FLEX/GRID',
      'Github',
      'GIT',
    ],
    link: 'https://menu-js-beyond.netlify.app/',
  },
  {
    id: 5,
    img: require('./imgs/tours.png'),
    title: 'Travel tours React',
    shortTitle: 'Tours',
    desc: 'Project built during my react course. Many functionalities (btns show more, delete specific tours',
    skills: ['React Js', 'HTML', 'CSS var()', 'Github', 'GIT'],
    link: 'https://travel-tours-react-beyond.netlify.app/',
  },
  {
    id: 6,
    img: require('./imgs/reviews.png'),
    title: 'Reviews React',
    shortTitle: 'Reviews',
    desc: 'Project built during my react course. Btns to display next and previous reviews, random reviews etc',
    skills: ['React Js', 'HTML', 'CSS var()', 'FLEX/GRID', 'Github', 'GIT'],
    link: 'https://reviews-react-beyond.netlify.app/',
  },
  {
    id: 7,
    img: require('./imgs/menu.png'),
    title: 'Restaurant menu React',
    shortTitle: 'Menu',
    desc: 'Project built during my React course, buttons are dynamic',
    skills: ['React Js', 'HTML', 'CSS var()', 'FLEX/GRID', 'Github', 'GIT'],
    link: 'https://menu-react-beyond.netlify.app/',
  },
  {
    id: 8,
    img: require('./imgs/profile.png'),
    title: 'Basic front end challenge',
    shortTitle: 'Profile card',
    desc: 'Project built while doing a front end challenge',
    skills: ['HTML', 'FLEX/GRID', 'Responsive Design'],
    link: 'https://basic-frontend-challenge-beyond.netlify.app/',
  },
];
export default projectsData;
